spring:
  datasource:
    url: jdbc:mysql://xxx:3306/dp?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver